### PR TITLE
created migration for removing null

### PR DESCRIPTION
**Pull request by tobold**
created a migration that when run will populate NULL values with specified defaults
(user with user_id = '9' is a placeholder user specially created on the production database)

The migration will:
- In 'users' table: set user_id = '9' where user_id is null
- In 'likes' table: set user_id = '9' where user_id is null
- In 'posts' table: set user_id = '9' where user_id is null
- In 'comments' table: set user_id = '9' where user_id is null
- In 'user' table: set first_name = '[name]' where first_name is null
- In 'user' table: set last_name = '[lastname]' where last_name is null
- In 'user' table: set occupation = '[occupation]' where occupation is null
- In 'user' table: set hometown = '[hometown]' where hometown is null
- In 'user' table: set date_of_birth = '1970-01-01 00:00:00' where date_of_birth is null
- In 'user' table: set bio = 'bio' where bio is null

### CODE REVIEW

**Comment by dearshrewdwit** [comment]
Have you tested this locally?

**Comment by dearshrewdwit** [comment]
@tobold let me know your results of the local db migration and then i'll approve

**Comment by tobold** [comment]
Migration worked on my cloned database:
image

_However_: I had to comment out the 'In 'comments' table: set user_id = '9' where user_id is null' line of the migration because the user_id column currently doesn't exist.

However after https://github.com/makersacademy/acebook-july2017/pull/26 is merged and migrated, the user_id column will exist on the production DB, so should remain.

NB: user 'b a' doesn't have null for their bio, occupation and hometown. It has a string; " "

**Review by dearshrewdwit — DISMISSED** [review]
merge when ready and don't forget to actually run the rake task on heroku

**Comment by dearshrewdwit** [comment]
@tobold please spend 5 mins documenting this process on the README.md

**Review by dearshrewdwit — APPROVED** [review]

**Pull request merged**
