### PR TITLE
Ci setup

### PR DESCRIPTION
**Pull request by kitkat119**
Added .travis.yml file for continuous integration.

Diagram of staging and production process:

### CODE REVIEW

**Review by dearshrewdwit — APPROVED** [review]
nice!!

**Review by tobold — APPROVED** [review]
Little green tick means travis is working, so I'm happy

**Comment by tobold** [comment]
Ah, tests now failing after it's been merged with master

**Comment by dearshrewdwit** [comment]
@tobold which means master was failing...

**Pull request merged**
